# Generated by Django 6.0.4 on 2026-04-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("invoice_overdue", "Invoice Overdue"),
                    ("proposal_deadline", "Proposal Deadline"),
                    ("project_due", "Project Due"),
                ],
                max_length=20,
            ),
        ),
    ]
