# Generated by Codex on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
